### ISSUE TITLE
colorsys is not defined

### ISSUE THREAD

**Issue by Ancoder2009** [PolyMarsDev/Flappuccino#11]
Traceback (most recent call last):
  File "C:\Users\Anthony admintrator\Desktop\Flappuccino-main\Flappuccino-main\main.py", line 277, in <module>
    main()
  File "C:\Users\Anthony admintrator\Desktop\Flappuccino-main\Flappuccino-main\main.py", line 161, in main
    o.setSprite(((player.position.y/50) % 100) / 100)
  File "C:\Users\Anthony admintrator\Desktop\Flappuccino-main\Flappuccino-main\background.py", line 9, in setSprite
    color = colorsys.hsv_to_rgb(tint,1,1)
NameError: name 'colorsys' is not defined
._.

**Comment by vlcoo** [comment]
Go to background.py and edit the first line so it reads:
`import pygame, colorsys`
That worked for me.

**Comment by LeWolfYT** [comment]
thanks

**Comment by ghost** [comment]
> Go to background.py and edit the first line so it reads:
> `import pygame, colorsys`
> That worked for me.

Yep this game is broken after my pull, I missed this but otherwise there are no errors whatsoever :/

**Comment by red-socks294** [comment]
Or, you don’t have Colorsys installed (or I am just thinking that it’s a pip package)

**Comment by byemc** [comment]
> Or, you don’t have Colorsys installed (or I am just thinking that it’s a pip package)

I think it's built into python, like `random`, `argparse` or `json`.

This is my clean Ubuntu WSL installation. As you can see, `colorsys` imported, but not `sadsadas` as it doesn't exist. 

![image](https://user-images.githubusercontent.com/77801870/115284901-27f33e00-a145-11eb-9a95-bff5d6ccc31e.png)

**Comment by red-socks294** [comment]
Yeah, that really proves it. Just reinstall Python.


Btw, I use WSL all the time.
________________________________

**Comment by syskill-the-coder** [comment]
Its not needed, you can just delete it lol

**Comment by byemc** [comment]
> Its not needed, you can just delete it lol

Sorry, what isn't? The game won't really work without it iirc

**Comment by meetshah1205** [comment]
Same thing happened to me, I solved it by going to <b style="color:blue;">background.py</b> and just putting:
<span style="color:blue;">`import colorsys`</span>
On the top.

**Comment by meetshah1205** [comment]
> Or, you don’t have Colorsys installed (or I am just thinking that it’s a pip package)

No its not
